#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

MACOS_TARGETS=aarch64-apple-ios

TARGET_DIR=`cargo metadata --format-version 1 --no-deps | jq ".target_directory" | xargs echo`
PROJECT_NAME=`cargo metadata --format-version 1 | jq ".resolve.root" | xargs echo | cut -d ' ' -f1`
LIB_NAME=$PROJECT_NAME.wasm

# <root>/target/universal/debug
WASM_DEBUG_DIR="$TARGET_DIR/wasm32-wasi/debug"
FLUTTER_WEB_DIR="$DIR/../plugin/web"
FLUTTER_MACOS_DIR="$DIR/../plugin/macos"

WASM_SOURCE_FILE="$WASM_DEBUG_DIR/$LIB_NAME"
# LIB_TARGET_FILE="$FLUTTER_WEB_DIR/$LIB_NAME"
LIB_TARGET_FILE="$FLUTTER_MACOS_DIR/$LIB_NAME"

cargo build --target wasm32-wasi --lib

cp $WASM_SOURCE_FILE $LIB_TARGET_FILE
